name: Backend - Build & Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew build

      - name: Run tests
        working-directory: ./backend
        run: ./gradlew test

      - name: Package the application
        working-directory: ./backend
        run: ./gradlew bootJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: job-interview-tracker-backend
          path: ./backend/build/libs/*[!plain].jar

          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          appdir: backend
          buildpacks: 'https://github.com/heroku/heroku-buildpack-gradle.git'
