name: Backend build, test and deploy to Heroku

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew build

      - name: Run tests
        working-directory: ./backend
        run: ./gradlew test

      - name: Package the application
        working-directory: ./backend
        run: ./gradlew bootJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: job-interview-tracker-backend
          path: build/libs/*jar

      - name: Publish to GitHub Packages
        working-directory: ./backend
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
